### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/pako#7]
Hi to anyone following this repo.

With the addition of support for a range of package managers by @PureTryOut, @emphasize and @LyesSaadi  I thought we were well overdue for a new release - presumably v0.3.0.

Just wanted to flag this before I do it in case anyone was just about to create a PR?

If I don't hear anything I'll increment the version number, tag a new release, and publish to PyPI one week from today.

**Comment by PureTryOut** [comment]
12 days later, could you make that release @krisgesling? :smile:

**Comment by krisgesling** [comment]
It is done :+1:
